### PR TITLE
fix(telephony.line.phone.programmablekeys): keys natural sort

### PR DESCRIPTION
**Pull request by julieni**
### Description of the Change

Keys are now sorted in natural order

### CODE REVIEW

**Comment by JeremyDec** [comment]
Hello @julieni, thanks for your contribution !

We will take in charge your fix, and keep you in touch once it will be applied

**Comment by julieni** [comment]
Hello @JeremyDec, I saw your changes in https://github.com/ovh-ux/manager/pull/1268, thanks for improvements ;)
BTW, should we submit PR in repo https://github.com/ovh-ux/manager or separate repos ?

**Comment by JeremyDec** [comment]
Hello, for the telecom part of the manager, you should submit PR into the new repo => https://github.com/ovh-ux/manager. 

If the part you want to change/fix is not present in this repository, you can make your PR in the https://github.com/ovh-ux/ovh-manager-xxxxx one.

You're welcome :)

**Comment by jleveugle** [comment]
Hello @julieni,
Your pull request is now closed due to inactivity.
Feel free to re-open it if you have any update.
Anna Bot for OVH UX <3

**Comment by julieni** [comment]
Hi,
as this PR is closed, it seems it's replaced by https://github.com/ovh-ux/manager/pull/1268, also closed now, and then #1512 which is still open.
But still no merge in develop or master, and no push in production.
OVH team, do you have an ETA for this patch to land in production ? Thanks.

**Comment by antleblanc** [comment]
Hi @julieni!

Thanks for submitting this Pull request.

As @JeremyDec said, we are in fact trying to move this repository into another one that will group all applications that rely on the Control Panel. But we are still working on it that's why we need to do some extra synchronization actions (replicate your fix into our monorepo).

I send your patch to our Quality Check Team to get a feedback in order to be able to merge it.

I will keep you posted, Thanks!

**Comment by antleblanc** [comment]
@julieni I was notified by @euhmeuh that your fix has been picked and improved in this following Pull request: #1512 (_we kept your commit._)

So I close this pull request.

Thanks again for your contribution. I will keep you posted as soon as the fix is deployed.

Thanks!

**Comment by antleblanc** [comment]
@julieni Patch has been deployed.

Thanks!

**Pull request closed without merging**
