### PR TITLE
build(*): clean useless files

### PR DESCRIPTION
**Pull request by jleveugle**

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report build-yarn#265.0 ✘  
* Stage 1
  * deps ✔ 
* Stage 2
  * build ✘  
  * test ✘

**Comment by ovh-cds** [comment]
CDS Report build-yarn#266.0 ✘  
* Stage 1
  * deps ✔ 
* Stage 2
  * build ✘  
  * test ✘

**Comment by antleblanc** [comment]
Just pay attention that you are removing this existing documentation: https://ovh-ux.github.io/ovh-manager-telecom :)

**Comment by jleveugle** [comment]
Yes @antleblanc, do you use it ?

**Comment by ovh-cds** [comment]
CDS Report build-yarn#275.0 ✘  
* Stage 1
  * deps ✔ 
* Stage 2
  * build ✘  
  * test ✘

**Comment by ovh-cds** [comment]
CDS Report build-yarn#275.1 ✘  
* Stage 1
  * deps ✔ 
* Stage 2
  * build ✘  
  * test ✘

**Comment by ovh-cds** [comment]
CDS Report build-yarn#275.2 ✘  
* Stage 1
  * deps ✔ 
* Stage 2
  * build ✘  
  * test ✔

**Comment by ovh-cds** [comment]
CDS Report build-yarn#279.0 ✘  
* Stage 1
  * deps ✔ 
* Stage 2
  * build ✘  
  * test ✔

**Comment by ovh-cds** [comment]
CDS Report build-yarn#284.0 ✘  
* Stage 1
  * deps ✔ 
* Stage 2
  * build ✘  
  * test ✔

**Comment by ovh-cds** [comment]
CDS Report build-yarn#287.0 ✘  
* Stage 1
  * deps ✔ 
* Stage 2
  * build ✘  
  * test -

**Comment by antleblanc** [comment]
@jleveugle This part of the documentation cover a tiny (very small chunk) of the VoIP section.

It's basically auto-generated by using `grunt-ngdocs`.

I didn't notice the first time I reviewed your changes, you are targeting `chore/webpack` branch. So we can handle it in a near future.

Let's say that my previous comments act as a reminder :)

**Comment by ovh-cds** [comment]
CDS Report build-yarn#288.0 ✘  
* Stage 1
  * deps ✔ 
* Stage 2
  * build ✘  
  * test ✔

**Comment by ovh-cds** [comment]
CDS Report build-yarn#289.0 ✘  
* Stage 1
  * deps ✔ 
* Stage 2
  * build ✘  
  * test ✔

**Comment by ovh-cds** [comment]
CDS Report build-yarn#295.0 ✘  
* Stage 1
  * deps ✔ 
* Stage 2
  * build ✘  
  * test ✔

**Comment by ovh-cds** [comment]
CDS Report build-yarn#299.0 ✘  
* Stage 1
  * deps ✔ 
* Stage 2
  * build ✘  
  * test ✔

**Comment by ovh-cds** [comment]
CDS Report build-yarn#300.0 ✘  
* Stage 1
  * deps ✔ 
* Stage 2
  * build ✘  
  * test ✔

**Comment by ovh-cds** [comment]
CDS Report deploy_uxci_eu#301.0 ✘  
* deploy_uxci
  * deploy_uxci ✘

**Comment by ovh-cds** [comment]
CDS Report deploy_uxci_eu#302.0 ✘  
* deploy_uxci
  * deploy_uxci ✘

**Comment by ovh-cds** [comment]
CDS Report deploy_uxci_eu#305.0 ✘  
* deploy_uxci
  * deploy_uxci ✘

**Pull request merged**
