### PR TITLE
fix(yarn): new-version parameter

### PR DESCRIPTION
**Pull request by JeremyDec**
## Build node new version parameter

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report build#6102.0 ✘  
* init
  * deps ✘

**Comment by euhmeuh** [comment]
Approved

**Comment by JeremyDec** [comment]
I think you can approve

**Comment by ovh-cds** [comment]
CDS Report build#6103.0 ✘  
* init
  * deps ✘

**Pull request merged**
