### PR TITLE
build: add __NG_APP_INJECTIONS__ to facilitate module injection

### PR DESCRIPTION
**Pull request by antleblanc**
# Add `__NG_APP_INJECTIONS__` to facilitate module injection

## ⚙️ Build

3d743db - build: add __NG_APP_INJECTIONS__ to facilitate module injection

## 🏠 Internal

- No QC required.

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report build-manager#1769.0 ✘  
* Stage 1
  * Build dependencies and inject Sentry ✔ 
* Stage 2
  * Build manager CA ✔ 
  * Build manager EU ✔ 
  * Build manager US ✔ 
  * Tests ✔ 
* Stage 3
  * Prepare tar.gz for UXCI / Release ✘

**Comment by ovh-cds** [comment]
CDS Report build-manager#1769.1 ✘  
* Stage 1
  * Build dependencies and inject Sentry ✔ 
* Stage 2
  * Build manager CA ✔ 
  * Build manager EU ✔ 
  * Build manager US ✔ 
  * Tests ✔ 
* Stage 3
  * Prepare tar.gz for UXCI / Release ✘

**Comment by ovh-cds** [comment]
CDS Report build-manager#1772.0 ✘  
* Stage 1
  * Build dependencies and inject Sentry ✔ 
* Stage 2
  * Build manager CA ✔ 
  * Build manager EU ✔ 
  * Build manager US ✔ 
  * Tests ✔ 
* Stage 3
  * Prepare tar.gz for UXCI / Release ✘

**Comment by jleveugle** [comment]
Hello @antleblanc,
Your pull request is now closed due to inactivity.
Feel free to re-open it if you have any update.
Anna Bot for OVH UX <3

**Pull request closed without merging**
